### ISSUE TITLE
Version 1.4.3 fail on intelliJ 2017.1.6 at startup

### ISSUE THREAD

**Issue by ciroanacleto** [Darkyenus/DarkyenusTimeTracker#23]
After upgrade to the last plugin version, 1.4.3,  my intellij 2017.1.6 fail to start with the following log:

Plugin

 'com.darkyen.darkyenustimetracker' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.AbstractMethodError: Method com/darkyen/TimeTrackerDefaultSettingsComponent.initComponent()V is abstract
    at com.darkyen.TimeTrackerDefaultSettingsComponent.initComponent(TimeTrackerDefaultSettingsComponent.java)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:491)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:466)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:425)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:411)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:63)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by Darkyenus** [comment]
Thanks for reporting. Could you please try attached build? I am not sure if that is the only place that is broken, so I don't want to do another release yet, and I don't have 2017.1.6 installed for testing. It is a build of 2dc429241afb18075a4d57e4e64be08aaeb99b71 (in extra .zip, because GitHub doesn't like .jars in comments).

[DarkyenusTimeTracker.jar.zip](https://github.com/Darkyenus/DarkyenusTimeTracker/files/2788463/DarkyenusTimeTracker.jar.zip)

**Comment by ciroanacleto** [comment]
It worked. Only a little problem occurred with minus character on decrement time button:
![timetracker](https://user-images.githubusercontent.com/3718512/51638664-1f036a00-1f46-11e9-9bb5-c3a9c5851e83.jpg)

**Comment by Darkyenus** [comment]
1.4.6 will support IDE versions 2020.1 and up. The version uploaded two comments above will have to suffice as a workaround for anyone on older IDE versions.
