### ISSUE TITLE
Deprecated use in version 1.5.3

### ISSUE THREAD

**Issue by marcelomonteironosi** [Darkyenus/DarkyenusTimeTracker#50]
Hello.
I am using the version 1.5.3 of the plugin in Intellij IDEA Community Edition 2024.1, and the following exception occurred:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.darkyen.actions.ResetGitTimeAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.darkyen.darkyenustimetracker]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by jhob101** [comment]
Also experiencing this issue in 2024.2.1.  Will a fix be released?
